name: Go
on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Print me
        run: echo you got your codes ya hacker
  deploy-stage:
    name: stage
    runs-on: ubuntu-latest
    needs: build
    environment: stage
    steps:
      - name: say stage
        run: echo environment is stage
  deploy-prod:
    name: prod
    runs-on: ubuntu-latest
    needs: [build, deploy-stage]
    environment: prod
    steps:
      - name: say prod
        run: echo environment is prod