name: Devices CRDB Schema Migrations Prod

on:
  push:
      tags:
        - "*-labs-devices-ent"
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Print me
        run: echo you got your codes ya hacker
  deploy-prod:
    name: prod
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: say prod
        run: echo environment is prod